version: '3.8'

services:
  backend:
    build: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data:/app/data
    environment:
      - FLASK_ENV=production

  frontend:
    build: frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:5000/api/submit
    depends_on:
      - backend